"""Seed script for CRM Leads module data.
Run from the backend directory: uv run python seed_leads.py
"""
from database import supabase


LEADS = [
    {
        "company_name": "Acme Technologies Inc.",
        "first_name": "Ricardo",
        "last_name": "Santos",
        "contact_name": "Ricardo Santos",
        "designation": "CTO",
        "email": "ricardo.santos@acmetech.ph",
        "mobile_number": "+63 917 123 4001",
        "lead_source": "Website",
        "lead_status": "New",
        "interest_level": "High",
        "remarks": "Interested in ERP implementation for their logistics division.",
    },
    {
        "company_name": "Pacific Blue Shipping Co.",
        "first_name": "Maricel",
        "last_name": "Tan",
        "contact_name": "Maricel Tan",
        "designation": "Operations Manager",
        "email": "maricel.tan@pacificblue.com",
        "mobile_number": "+63 918 234 5002",
        "lead_source": "Referral",
        "lead_status": "Contacted",
        "interest_level": "Medium",
        "remarks": "Referred by existing client KSI. Needs inventory tracking.",
    },
    {
        "company_name": "Golden Dragon Construction",
        "first_name": "Wei",
        "last_name": "Chen",
        "contact_name": "Wei Chen",
        "designation": "Project Director",
        "email": "wei.chen@goldendragon.ph",
        "mobile_number": "+63 919 345 6003",
        "lead_source": "Trade Show",
        "lead_status": "Qualified",
        "interest_level": "High",
        "remarks": "Met at PhilConstruct 2026. Looking for project management + payroll module.",
    },
    {
        "company_name": "Sunrise Medical Supplies",
        "first_name": "Angela",
        "last_name": "Reyes",
        "contact_name": "Angela Reyes",
        "designation": "Procurement Head",
        "email": "angela.reyes@sunrisemedical.ph",
        "mobile_number": "+63 920 456 7004",
        "lead_source": "Cold Call",
        "lead_status": "New",
        "interest_level": "Low",
        "remarks": "Currently using SAP but exploring cheaper alternatives.",
    },
    {
        "company_name": "NovaTech Solutions",
        "first_name": "Jerome",
        "last_name": "Villanueva",
        "contact_name": "Jerome Villanueva",
        "designation": "CEO",
        "email": "jerome@novatech.io",
        "mobile_number": "+63 921 567 8005",
        "lead_source": "LinkedIn",
        "lead_status": "Contacted",
        "interest_level": "High",
        "remarks": "Startup scaling fast. Needs full ERP from day one.",
    },
    {
        "company_name": "Metro Fresh Foods Corp.",
        "first_name": "Diana",
        "last_name": "Cruz",
        "contact_name": "Diana Cruz",
        "designation": "Finance Manager",
        "email": "diana.cruz@metrofresh.ph",
        "mobile_number": "+63 922 678 9006",
        "lead_source": "Website",
        "lead_status": "Qualified",
        "interest_level": "Medium",
        "remarks": "Interested in AR/AP modules. Wants demo next week.",
    },
    {
        "company_name": "CloudVault IT Services",
        "first_name": "Patrick",
        "last_name": "Lim",
        "contact_name": "Patrick Lim",
        "designation": "Managing Director",
        "email": "patrick.lim@cloudvault.ph",
        "mobile_number": "+63 923 789 0007",
        "lead_source": "Referral",
        "lead_status": "Proposal Sent",
        "interest_level": "High",
        "remarks": "Proposal sent for HR + Payroll module. Follow up by end of week.",
    },
    {
        "company_name": "Isla Verde Resorts",
        "first_name": "Carmen",
        "last_name": "Dela Rosa",
        "contact_name": "Carmen Dela Rosa",
        "designation": "General Manager",
        "email": "carmen@islaverde.ph",
        "mobile_number": "+63 917 890 1008",
        "lead_source": "Email Campaign",
        "lead_status": "New",
        "interest_level": "Medium",
        "remarks": "Hospitality group with 3 properties. Needs multi-entity support.",
    },
    {
        "company_name": "PhilSteel Manufacturing",
        "first_name": "Roberto",
        "last_name": "Aquino",
        "contact_name": "Roberto Aquino",
        "designation": "Plant Manager",
        "email": "roberto.aquino@philsteel.com.ph",
        "mobile_number": "+63 918 901 2009",
        "lead_source": "Trade Show",
        "lead_status": "Contacted",
        "interest_level": "High",
        "remarks": "Heavy manufacturing. Needs inventory + purchasing + GL.",
    },
    {
        "company_name": "BrightPath Education",
        "first_name": "Sophia",
        "last_name": "Mendoza",
        "contact_name": "Sophia Mendoza",
        "designation": "Admin Director",
        "email": "sophia@brightpath.edu.ph",
        "mobile_number": "+63 919 012 3010",
        "lead_source": "Website",
        "lead_status": "Unqualified",
        "interest_level": "Low",
        "remarks": "Small school. Budget too limited for full ERP. May revisit next year.",
    },
    {
        "company_name": "Visayan Agri Corp.",
        "first_name": "Manuel",
        "last_name": "Gonzales",
        "contact_name": "Manuel Gonzales",
        "designation": "VP Operations",
        "email": "manuel.gonzales@visayanagri.ph",
        "mobile_number": "+63 920 123 4011",
        "lead_source": "Cold Call",
        "lead_status": "Qualified",
        "interest_level": "Medium",
        "remarks": "Agricultural export company. Interested in tax management and LOA module.",
    },
    {
        "company_name": "Quantum Dynamics PH",
        "first_name": "Rina",
        "last_name": "Garcia",
        "contact_name": "Rina Garcia",
        "designation": "IT Manager",
        "email": "rina.garcia@quantumdynamics.ph",
        "mobile_number": "+63 921 234 5012",
        "lead_source": "LinkedIn",
        "lead_status": "New",
        "interest_level": "High",
        "remarks": "Tech company expanding. Evaluating ERP solutions this quarter.",
    },
    {
        "company_name": "Heritage Bank Philippines",
        "first_name": "Antonio",
        "last_name": "Bautista",
        "contact_name": "Antonio Bautista",
        "designation": "SVP Technology",
        "email": "antonio.bautista@heritagebank.ph",
        "mobile_number": "+63 922 345 6013",
        "lead_source": "Referral",
        "lead_status": "Proposal Sent",
        "interest_level": "High",
        "remarks": "Enterprise-level deal. Needs compliance features and audit trail.",
    },
    {
        "company_name": "Green Energy PH Inc.",
        "first_name": "Bianca",
        "last_name": "Flores",
        "contact_name": "Bianca Flores",
        "designation": "Finance Director",
        "email": "bianca.flores@greenenergy.ph",
        "mobile_number": "+63 923 456 7014",
        "lead_source": "Email Campaign",
        "lead_status": "Contacted",
        "interest_level": "Medium",
        "remarks": "Renewable energy startup. Looking at GL and financial reporting.",
    },
    {
        "company_name": "Manila Bay Logistics",
        "first_name": "Enrique",
        "last_name": "Ramos",
        "contact_name": "Enrique Ramos",
        "designation": "Logistics Head",
        "email": "enrique@manilabaylogistics.com",
        "mobile_number": "+63 917 567 8015",
        "lead_source": "Website",
        "lead_status": "New",
        "interest_level": "Medium",
        "remarks": "Freight forwarding company. Needs purchasing and inventory modules.",
    },
    {
        "company_name": "Cebu Digital Agency",
        "first_name": "Kristine",
        "last_name": "Ong",
        "contact_name": "Kristine Ong",
        "designation": "CEO",
        "email": "kristine@cebudigital.ph",
        "mobile_number": "+63 918 678 9016",
        "lead_source": "LinkedIn",
        "lead_status": "Qualified",
        "interest_level": "High",
        "remarks": "Digital marketing agency with 50+ staff. Needs HR + project management.",
    },
    {
        "company_name": "Davao Fresh Produce",
        "first_name": "Mark",
        "last_name": "Tan",
        "contact_name": "Mark Tan",
        "designation": "Owner",
        "email": "mark.tan@davaofresh.ph",
        "mobile_number": "+63 919 789 0017",
        "lead_source": "Cold Call",
        "lead_status": "Contacted",
        "interest_level": "Low",
        "remarks": "Small business. May only need invoicing module.",
    },
    {
        "company_name": "Pinnacle Insurance Group",
        "first_name": "Victoria",
        "last_name": "Sy",
        "contact_name": "Victoria Sy",
        "designation": "COO",
        "email": "victoria.sy@pinnacleins.ph",
        "mobile_number": "+63 920 890 1018",
        "lead_source": "Referral",
        "lead_status": "Negotiation",
        "interest_level": "High",
        "remarks": "Large insurance group. In contract negotiation for full ERP suite.",
    },
]


def seed():
    print("[SEED] Seeding 18 mock leads...")

    # Clear existing leads (optional — comment out if you want to append)
    existing = supabase.table("leads").select("lead_id").execute().data
    if existing:
        print(f"   [!] Found {len(existing)} existing leads. Inserting new ones alongside them.")

    # Insert all leads
    result = supabase.table("leads").insert(LEADS).execute()

    if result.data:
        print(f"   [OK] Successfully inserted {len(result.data)} leads.")
        for lead in result.data:
            print(f"      - [{lead['lead_id']}] {lead['company_name']} -- {lead['lead_status']}")
    else:
        print("   [FAIL] Insert failed -- no data returned.")

    print("\n[DONE] Lead seeding complete!")


if __name__ == "__main__":
    seed()
