export { CRMLayout } from './CRMLayout'
export { default as CustomerList } from './CustomerList'
export { default as Leads } from './Leads'
export { default as SalesActivities } from './SalesActivities'
export { default as SalesPipeline } from './SalesPipeline'
export { default as SalesForecast } from './SalesForecast'
export { default as SalesReports } from './SalesReports'
export { SalesOrderDetail } from './SalesOrderDetail'
export { SalesOrderList } from './SalesOrderList'
